version: "3.8"

services:
  bot:
    image: ghcr.io/thinvv770/val-checking/val-checking
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 6002:6002
    volumes:
      - ./config.json:/usr/app/config.json
      - ./data:/usr/app/data
    container_name: val-checking
